import { mutation } from "./_generated/server";

export const seedData = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("apis").first();
    if (existing) return "Already seeded";

    // Seed categories
    const categories = [
      { name: "AI & Machine Learning", slug: "ai", icon: "brain", color: "#8B5CF6" },
      { name: "Finance & Payments", slug: "finance", icon: "dollar", color: "#10B981" },
      { name: "Communication", slug: "communication", icon: "message", color: "#3B82F6" },
      { name: "Data & Analytics", slug: "data", icon: "chart", color: "#F59E0B" },
      { name: "Social Media", slug: "social", icon: "users", color: "#EC4899" },
      { name: "Weather & Geo", slug: "weather", icon: "cloud", color: "#06B6D4" },
      { name: "Entertainment", slug: "entertainment", icon: "play", color: "#EF4444" },
      { name: "E-Commerce", slug: "ecommerce", icon: "cart", color: "#84CC16" },
    ];

    for (const cat of categories) {
      await ctx.db.insert("categories", { ...cat, apiCount: 0 });
    }

    // Seed APIs
    const apis = [
      {
        name: "OpenAI GPT",
        description: "Access GPT-4 and other powerful language models for text generation, analysis, and conversation.",
        category: "ai",
        baseUrl: "https://api.openai.com/v1",
        documentationUrl: "https://platform.openai.com/docs",
        authType: "bearer",
        isPublic: true,
        isFree: false,
        tags: ["ai", "nlp", "gpt", "chatbot"],
        upvotes: 2847,
        createdAt: Date.now(),
      },
      {
        name: "Anthropic Claude",
        description: "Claude AI API for safe, helpful, and honest AI assistants with advanced reasoning capabilities.",
        category: "ai",
        baseUrl: "https://api.anthropic.com/v1",
        documentationUrl: "https://docs.anthropic.com",
        authType: "api_key",
        isPublic: true,
        isFree: false,
        tags: ["ai", "nlp", "claude", "assistant"],
        upvotes: 2156,
        createdAt: Date.now(),
      },
      {
        name: "Stripe",
        description: "Complete payment processing platform for online businesses. Accept payments, manage subscriptions.",
        category: "finance",
        baseUrl: "https://api.stripe.com/v1",
        documentationUrl: "https://stripe.com/docs/api",
        authType: "api_key",
        isPublic: true,
        isFree: false,
        tags: ["payments", "subscriptions", "billing"],
        upvotes: 3421,
        createdAt: Date.now(),
      },
      {
        name: "Twilio",
        description: "Cloud communications platform for SMS, voice, video, and authentication APIs.",
        category: "communication",
        baseUrl: "https://api.twilio.com",
        documentationUrl: "https://www.twilio.com/docs",
        authType: "api_key",
        isPublic: true,
        isFree: false,
        tags: ["sms", "voice", "messaging", "2fa"],
        upvotes: 1893,
        createdAt: Date.now(),
      },
      {
        name: "SendGrid",
        description: "Email delivery service for transactional and marketing emails at scale.",
        category: "communication",
        baseUrl: "https://api.sendgrid.com/v3",
        documentationUrl: "https://docs.sendgrid.com",
        authType: "api_key",
        isPublic: true,
        isFree: true,
        tags: ["email", "marketing", "transactional"],
        upvotes: 1567,
        createdAt: Date.now(),
      },
      {
        name: "Twitter/X API",
        description: "Access Twitter data, post tweets, and build integrations with the X platform.",
        category: "social",
        baseUrl: "https://api.twitter.com/2",
        documentationUrl: "https://developer.twitter.com/docs",
        authType: "oauth",
        isPublic: true,
        isFree: false,
        tags: ["social", "twitter", "posts", "analytics"],
        upvotes: 2234,
        createdAt: Date.now(),
      },
      {
        name: "Spotify Web API",
        description: "Access Spotify music catalog, user playlists, playback control, and recommendations.",
        category: "entertainment",
        baseUrl: "https://api.spotify.com/v1",
        documentationUrl: "https://developer.spotify.com/documentation/web-api",
        authType: "oauth",
        isPublic: true,
        isFree: true,
        tags: ["music", "streaming", "playlists"],
        upvotes: 1876,
        createdAt: Date.now(),
      },
      {
        name: "OpenWeatherMap",
        description: "Weather data API with current conditions, forecasts, and historical weather data.",
        category: "weather",
        baseUrl: "https://api.openweathermap.org/data/2.5",
        documentationUrl: "https://openweathermap.org/api",
        authType: "api_key",
        isPublic: true,
        isFree: true,
        tags: ["weather", "forecast", "climate"],
        upvotes: 1456,
        createdAt: Date.now(),
      },
      {
        name: "Google Maps Platform",
        description: "Maps, routes, places, and geolocation services for web and mobile applications.",
        category: "weather",
        baseUrl: "https://maps.googleapis.com/maps/api",
        documentationUrl: "https://developers.google.com/maps/documentation",
        authType: "api_key",
        isPublic: true,
        isFree: false,
        tags: ["maps", "geolocation", "directions", "places"],
        upvotes: 2567,
        createdAt: Date.now(),
      },
      {
        name: "Shopify Admin API",
        description: "Build apps and integrations for Shopify stores. Manage products, orders, and customers.",
        category: "ecommerce",
        baseUrl: "https://{store}.myshopify.com/admin/api",
        documentationUrl: "https://shopify.dev/docs/api/admin",
        authType: "oauth",
        isPublic: true,
        isFree: false,
        tags: ["ecommerce", "store", "products", "orders"],
        upvotes: 1789,
        createdAt: Date.now(),
      },
      {
        name: "Plaid",
        description: "Financial data API for connecting bank accounts, verifying identity, and accessing transactions.",
        category: "finance",
        baseUrl: "https://production.plaid.com",
        documentationUrl: "https://plaid.com/docs",
        authType: "api_key",
        isPublic: true,
        isFree: false,
        tags: ["banking", "finance", "transactions", "identity"],
        upvotes: 1654,
        createdAt: Date.now(),
      },
      {
        name: "Mixpanel",
        description: "Product analytics API for tracking user behavior, events, and building funnels.",
        category: "data",
        baseUrl: "https://api.mixpanel.com",
        documentationUrl: "https://developer.mixpanel.com/docs",
        authType: "api_key",
        isPublic: true,
        isFree: true,
        tags: ["analytics", "tracking", "events", "funnels"],
        upvotes: 1234,
        createdAt: Date.now(),
      },
      {
        name: "Hugging Face",
        description: "Access thousands of ML models for NLP, computer vision, audio, and more.",
        category: "ai",
        baseUrl: "https://api-inference.huggingface.co",
        documentationUrl: "https://huggingface.co/docs/api-inference",
        authType: "bearer",
        isPublic: true,
        isFree: true,
        tags: ["ai", "ml", "nlp", "models"],
        upvotes: 1987,
        createdAt: Date.now(),
      },
      {
        name: "Discord",
        description: "Build bots and integrations for Discord servers. Manage messages, channels, and users.",
        category: "communication",
        baseUrl: "https://discord.com/api/v10",
        documentationUrl: "https://discord.com/developers/docs",
        authType: "bearer",
        isPublic: true,
        isFree: true,
        tags: ["chat", "bots", "community", "gaming"],
        upvotes: 2123,
        createdAt: Date.now(),
      },
      {
        name: "YouTube Data API",
        description: "Access YouTube videos, channels, playlists, and analytics data.",
        category: "entertainment",
        baseUrl: "https://www.googleapis.com/youtube/v3",
        documentationUrl: "https://developers.google.com/youtube/v3",
        authType: "api_key",
        isPublic: true,
        isFree: true,
        tags: ["video", "streaming", "youtube", "analytics"],
        upvotes: 2345,
        createdAt: Date.now(),
      },
    ];

    for (const api of apis) {
      await ctx.db.insert("apis", api);
    }

    return "Seeded successfully";
  },
});
